### ISSUE TITLE
Failure to run on Ubuntu 16.04.04 

### ISSUE THREAD

**Issue by Honestpuck** [liddiard/stream-editor#7]
I am attempting to get the project to run on Ubuntu 16.04.04.

I installed npm using apt-get and followed the instructions in the README. At the step `npm install && npm start` I get an error.

    watchify -v -o dist/bundle.js -t scssify -t reactify src/app.jsx

    /usr/bin/env: ‘node’: No such file or directory

    npm ERR! Linux 4.4.0-116-generic
    npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
    npm ERR! node v4.2.6
    npm ERR! npm  v3.5.2

I realise the project has not been touched in some time but I am eager to get it working as it's the only tool of it's kind I have been able to find.

**Comment by Honestpuck** [comment]
It turns out there is a fairly easy fix.

The problem is that `apt install npm` installs the program as `nodejs` rather than `node`.

Execute `sudo ln -s /usr/bin/nodejs /usr/bin/node` and this is fixed.

There is another small problem with the instructions in the README. If you clone the git repo it doesn't create the empty directory at `static/dist` so the write of `/dist/build.js` fails.

Before running `npm install && npm start` for the first time you need to `mkdir dist`

**Comment by liddiard** [comment]
@Honestpuck Well how's this for a late response? I apologize – I completely missed this issue back in 2018, but glad you got it worked out!

Going to close it as likely no longer applicable because I've entirely rewritten the frontend recently, and it's now being built with webpack instead of this browserify command.

You may also be interested to know that this project is now deployed at https://streameditor.io/ :)
